### PR TITLE
added support for opening old hawc style maptrees

### LINKED ISSUE #21: Old maptrees unable to open
Previously, we used integers, rather than strings to refer to the bins. They were labeled 'id' rather than 'name' as we have now. I can manually overcome this label switch, however due to the type difference, a fascinating error message occurs.

This was while running the example to extract an ROI 3 degrees around the crab, from the example in hal already (but for Mrk 421).

`Traceback (most recent call last):
  File "make_crab_set.py", line 18, in <module>
    m.write("crab_maptree.hd5")         
  File "/Users/chad/hawc/chad_hal/hawc_hal/maptree/map_tree.py", line 171, in write
    'Bin name inconsistency: {} != {}'.format(bin_id, analysis_bin.name)
AssertionError: Bin name inconsistency: 0 != 0`

### PR DESCRIPTION
**Pull request by cbrisboi**
This pull request is to fix #21.

### CODE REVIEW

**Comment by cbrisboi** [comment]
@henrikef  I was asking about these commits. I'll search for the other place in the code where this was addressed.

**Comment by cbrisboi** [comment]
in response.py, starting on line 195. I'll match the two to follow the same error messages

**Comment by henrikef** [comment]
Looks good to me. Apparently I worked on this previously, but only fixed it for the response file, not the maps. See 

https://github.com/threeML/hawc_hal/pull/2

https://github.com/threeML/hawc_hal/blob/3ec5e1fd8c635133cda2f5a93049967264a9c809/hawc_hal/response/response.py#L194

**Comment by henrikef** [comment]
Regarding the tests: Can you set the geminga paper test to xfail for now? It fails because parameters aren't automatically unlinked when a source is removed. Addresded in https://github.com/threeML/astromodels/pull/101 , but I need a bit of time to work on that pull request.

**Review by henrikef — APPROVED** [review]

**Pull request merged**
