### PR TITLE
Add a background column when plotting the planes.

### PR DESCRIPTION
**Pull request by colasri**
Display the background too.
Do not smooth the background with a Gaussian kernel, since we do want to know if the background (as used in the computation) is smooth enough or if there are issues.

### CODE REVIEW

**Comment by colasri** [comment]
display_fit
exemple

**Comment by giacomov** [comment]
Very nice!

Since you are at it, you might want to set the color scale (`vmin` and `vmax` keywords) to the same value for both model and excess, so they are easier to compare.

If not, I'll do it in a future commit.

**Comment by colasri** [comment]
I think this PR is ready to merge.

**Comment by giacomov** [comment]
ok, merging.

I see that the Travis Linux build is still failing here, probably you are behind a few commits from master.

It is fine for this fork, I'll merge anyway, but if you have other forks around make sure to go back in sync with master.

Thanks!

**Pull request merged**
