### PR TITLE
Futurizing hawc_hal for py3

### PR DESCRIPTION
**Pull request by hayalaso**
I use the `futurize` software to start making changes for `hawc_hal` to be able to run in py3. 
I was able to compile it in the miniconda3 environment and it seemed to install fine, and least it didn't give me syntax errors. 

I ran the tests with `pytest` (version 5.4.2). A few tests ran fine. I got one test (`test_copy.py`) that didn't pass due to the newer pytest version. I'm not very verse with pytest but I can keep looking into it. Other tests gave me some weird errors, like a ROOT file not being able  to close (when running `test_geminga_paper` for example). 

I still figure it would be good to start the conversion of hawc_hal to py3.
I'm requesting to merge to the master branch, but if any of the threeML group would like to make a py3 branch so that I can pull request there, that would work too, and more interested people could also look into updating the code.

### CODE REVIEW

**Comment by henrikef** [comment]
Awesome! 

Which `test_copy.py` failed? There's one that's known to fail (marked xfail), causing [the issue described here](../issues/1).

**Comment by henrikef** [comment]
Looks like the automated tests failed. Maybe the test environments need to be updated?

**Comment by hayalaso** [comment]
From `test_copy.py` the first one. I get this:

> __________________ test_deepcopy_point_source ___________________
> Fixture "maptree" called directly. Fixtures are not meant to be called directly,
> but are created automatically when test functions request them as parameters.

It's the pytest.fixture for maptree and response

**Comment by hayalaso** [comment]
I had a look at the automated test and it seems, that the package `past.utils` is not available during the check. I assume this might need to be installed by threeML members?

**Pull request merged**
